# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2016

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    TEST_TASKS: __[2.12.7].test

install:
  - SET MILL_URL=https://github.com/lihaoyi/mill/releases/download/0.3.3/0.3.3

build_script:
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - MD C:\bin
  - curl -Lo C:\bin\mill.bat %MILL_URL%

test_script:
  - cmd /C C:\bin\mill.bat -i all %TEST_TASKS%

cache:
  - '%LOCALAPPDATA%\Coursier\cache'
