# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012 R2

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    TEST_TASKS: __.jvm.__.test
  - JAVA_HOME: C:\Program Files\Java\jdk9
    TEST_TASKS: __.jvm.__.test

init:
  # Appveyor has so,e problems with symlinks..
  # https://github.com/appveyor/ci/issues/650#issuecomment-186592582
  - git config --global core.symlinks true

install:
  - SET MILLW_URL=https://raw.githubusercontent.com/lefou/millw/main/millw.bat

build_script:
  - SET "PATH=%JAVA_HOME%\bin;%PATH%"
  - MD C:\bin
  - curl -Lo C:\bin\mill.bat %MILLW_URL%

test_script:
  - cmd /C C:\bin\mill.bat -i all %TEST_TASKS%

cache:
  - '%LOCALAPPDATA%\Coursier\cache'
